server:
  port: 7070

spring:
  application:
    name: sevkiyat_backend
  profiles:
    active: "devlocal"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: SPRINGEGITIM
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
  datasource:
    jndi-name: jdbc/egitimDevDS
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 1000
      max-lifetime: 1000
      auto-commit: true
  open-in-view: false
  data:
    redis:
      repositories:
        enabled: false  
  redis:
    host: myscache.erdemir.erdgrp.intra
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
file:
  upload-dir: uploads

multipart:
  enabled: true

core:
  ommg:
    cache:
      timeout: 1200