server:
  port: 7070

spring:
  application:
    name: sevkiyat_backend
  profiles:
    active: "dev"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: SEVKIYAT
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
  datasource:
    jndi-name: jdbc/sevkDS
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 1000
      max-lifetime: 1000
      auto-commit: true
    open-in-view: false
  data:
    redis:
      repositories:
        enabled: false  
  redis:
    host: myscache.erdemir.erdgrp.intra
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
  cloud:
    config:
      uri: http://10.67.97.20:8888/config/cfg/master/sevkiyat/
      fail-fast: true
      username: root
      password: s3cr3t

file:
  upload-dir: uploads

multipart:
  enabled: true

core:
  ommg:
    cache:
      timeout: 1200

com:
  ommg:
    dys:
      api-url: https://apigwtest.erdemir.com.tr/int/dev/docent/dys    
    announce:
      api-url: https://apigwtest.erdemir.com.tr/int/dev/ns/api/v1/duyurular?
    message:
      api-url: https://apigwtest.erdemir.com.tr/int/dev/ns/api/v2/messageservice/
    aspect:
      enabled: true
    token:
      enabled: true
      endpoint: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-oauth-provider/oauth2/token
      client-id: d287ffa0-b01c-4aad-9635-6f983f95567f
      client-secret: pG2kF8bW0vB8rA1rF5oA2gF4qF8jA3wV8iI7cS1rO7cT8xG6kS
      username: 2889e00f-0b40-4d25-9927-34f1ca2bc904
      password: tXlp9hcsMVJw
      validation-url: https://apigwtest.erdemir.com.tr/int/dev/b2b/ent/esso2-entegrasyon-oauth-provider/oauth2/introspect
      check-time: 20
    ford-ftp:
      host: 195.46.152.3
      username: ersem
      password: 3rs3m
      file-dir: /fordoto/Outbox/
    euys-ftp:
      host: 10.67.1.81
      username: uysftp
      password: eruysdemir
      file-dir: /home/uysftp/uks/
    integration:
      transaction:
        prefix: SEV_BACKEND
      client:        
        arac-kamera-erdemir: https://apigwtest.erdemir.com.tr/int/dev/erdemir-kantar//WebServiceRest/PictureSrv.svc/Image        
        dosya:
          slab: https://apigwtest.erdemir.com.tr/int/dev/iuys/uysservis/service/sevkiyatIslemleri/slabSevkList
        eirsaliye:
          eirsaliye-gonder: https://apigwtest.erdemir.com.tr/int/dev/eirsent/e-irsaliye/e-irsaliye-gonder          
          eirsaliye-ciktisi-al: https://apigwtest.erdemir.com.tr/int/dev/eirsent/e-irsaliye/e-irsaliye-ciktisi-al/
          eirsaliye-gib-durum-al: https://apigwtest.erdemir.com.tr/int/dev/eirsent/e-irsaliye/e-irsaliye-gib-durumu-al-test-ortami/        
        esso:
          job-kullanici-id: 0
          rol-sorgula: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/rol/sorgula
          kullanici-yetkili-rol-liste: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicirol/yetkiliroller
          kullanici-yetkisiz-rol-liste: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicirol/yetkisizroller
          kullanici-gir: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/gir
          kullanici-guncelle: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/guncelle
          kullanici-bul: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/bul
          kullanici-bul-by-kullanici-adi: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/bul/uygulamakod/kullaniciadi?uygulamakod=%s&kullaniciadi=%s
          kullanici-sil: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/sil
          yetki-grup-model-liste: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/yetkigrupmodul/yetkigrupmoduller
          super-rol-sorgula: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidissuper/rol/kullanicidissuper/roller
          super-kullanici-yetkili-rol-liste: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidissuper/rol/kullanici/yetkiliroller
          super-kullanici-yetkisiz-rol-liste: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidissuper/rol/kullanici/yetkisizroller
          super-kullanici-gir: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidissuper/kullanici/gir
          super-kullanici-guncelle: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidis/guncelle
          super-kullanici-sil: https://apigwtest.erdemir.com.tr/int/dev/esso2-entegrasyon-dis-sistem/dissistem/kullanicidissuper/kullanici/sil
          rol-kodu:
            sevkiyat-sistem-sorumlusu: ef109085-93ad-47cf-bf45-7a983481a71e
            sevkiyat-yetkili-kullanici: b8261bbd-c098-4f45-adcf-b1c70c635181
            sevkiyat-uzmani: 46648fd9-9e39-41c0-8a01-6be8f620ae1d
            nakliyeci-firma-sorumlusu: 488f04e6-f546-41f8-8f05-5f689ed6851c
            nakliyeci-mobil-surucu: 0920da3a-5cac-48e3-aadb-4b73a2d964bd
            sevkiyat-erdemir-ihracaat-satis-uzmani: d5518f77-0595-4e77-8c35-c3151042075e
            sevkiyat-isdemir-ihracaat-satis-uzmani: 3d08428c-18de-4a73-9a2d-b439928f6a45
            sevkiyat-erdemir-yurt-ici-satis-uzmani: 8a283791-f718-49d5-941d-66253803335d
            sevkiyat-isdemir-yurt-ici-satis-uzmani: 0d014917-0f7c-4766-a538-54239fce6a6a
            sevkiyat-ssh-yetkilisi: 61fd074e-f638-4832-bbed-7aa856eb6e9b
            sevkiyat-kantar-sorumlusu: cd2657e2-b4d8-4315-a2de-f655877a4e19
            sevkiyat-forklift-operatoru: d7d92baf-6679-4e1f-9fb5-78247b782a67
            sevkiyat-yan-urun-satis-uzmani: 20a2e65e-24b9-4328-a53d-9707edbdc14f
            sevkiyat-vinc-operatoru: 6e32ff8f-ac2e-4032-b774-9555cc7a1334
            sevkiyat-uzmani-muhendisi: 11db58f7-8eff-4a6e-95a1-7be068a3eac7
            sevkiyat-isdemir-vardiya-amiri: f95e6558-5c0e-4a1b-a363-14a8021b80e5
            sevkiyat-isdemir-formeni: cf6747d8-0f1a-4e3d-92d8-6521a6bc3eec
        etiket:          
          yariMamulAmbarlama: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/yariMamulAmbarlama
          yariMamulAmbarlamaIptal: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/yariMamulAmbarlamaIptal
          uretimAmbarlama: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/uretimAmbarlama
          uretimAmbarlamaIptal: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/uretimAmbarlamaIptal
          depoBultenAmbarlama: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/depoBultenAmbarlama
          fasonYariMamulAmbarlama: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/fasonYariMamulAmbarlama
          fasonYariMamulTuketMamulYMUret: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/fasonYariMamulTuketMamulYMUret          
          getEtiketIadeKabulu: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketIadeKabulu
          getEtiketAmbarlandi: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketAmbarlandi
          getEtiketSevkAsamasinda: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketSevkAsamasinda
          getEtiketSevkAsamasindaIptal: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketSevkAsamasindaIptal
          getEtiketGCSBBagla: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketGCSBBagla
          etiketGCSBIptal: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/etiketGCSBIptal
          getEtiketIadeKaydi: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketIadeKaydi
          etiketDokumAnalizBilgileri: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/dissistemler/sevkiyat/etiketYarimamulDokumAnalizBilgileri
          hazirBultenAgirlikGetir: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/bultenyonetimi/hazirBultenAgirlikGetir
          etiketMusteriIade: https://apigwtest.erdemir.com.tr/int/dev/euysent/uysservis/service/sevkiyatIslemleri/etiketMusteriIade
          isdemirdenGelenBobin: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/sevkiyatServisleriApi/isdemirdenGelenBobin
          erdemirdenGelenBobin: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/erdemirdenGelenBobin
        hes-kodu: https://apigwtest.erdemir.com.tr/int/dev/hes/kontrol/heskodu/%s
        is-emri-erdemir:
          nakliye-kaydet: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/mtfApi/erdNakliyeBilgileriniKaydet
          nakliye-is-emri-iptal: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/IsEmriApi/nakliyeIsEmriIptal
          liman-kaydet: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/IsEmriApi/erdS3IsEmriOlustur
          vinc-aktiflestir: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/vincApi/vincAktiflestir
          vinc-durdur: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/vincApi/vincDurdur
          iptal: https://apigwtest.erdemir.com.tr/int/dev/ebsys-sevk-api/ebsyssevk-be/api/IsEmriApi/erdS3IsEmriIptal
        is-emri-isdemir:
          nakliye-kaydet: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/nakliyeIsemriKaydet
          nakliye-is-emri-iptal: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/nakliyeIsEmriIptalEt
          liman-kaydet: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/isEmriKaydet
          vinc-aktiflestir: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/vincAktiflestir
          vinc-durdur: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/vincDurdur
          iptal: https://apigwtest.erdemir.com.tr/int/dev/ibsys-sevk-api/IHS3WebService/s3service/IBOBINSTOKS3Service/isEmriIptal
        kantar-oku:
          erdemir: https://apigwtest.erdemir.com.tr/int/dev/erdemir-kantar/ws660/api/kantarOku
          isdemir: https://apigwtest.erdemir.com.tr/int/dev/ots-umsat-ent/IsdemirWebServis/kantarOku
        lys:
          gemi-senkronize-et: https://apigwtest.erdemir.com.tr/int/dev/lysent/lys-servis/gemi/senkronize
        rezervasyon:
          erdemir-bulten-oncesi-rezervasyon: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getBultenOncesiRezervasyon
          erdemir-bulten-oncesi-rezervasyon-iptal: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getBultenOncesiRezervasyonIptal
          erdemir-bulten-rezervasyon: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getBultenRezervasyon
          erdemir-bulten-rezervasyon-iptal: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getBultenRezervasyonIptal
        sap-fatura:
          fatura-olustur: https://apigwtest.erdemir.com.tr/int/dev/fatura/olustur
          iade-fatura-olustur: https://apigwtest.erdemir.com.tr/int/dev/sevkiyat/iade-puantaj/gonder
          mf-fatura-bilgisi-getir: https://apigwtest.erdemir.com.tr/int/dev/sap-mf-fatura-bilgisi/getir
        sap-personel:
          #organizasyon-liste: http://10.67.97.20:32737/api/v1/sap/organizasyonservice/organizasyonlar
          #personel-list-by-firma-kodu: http://10.67.97.20:32737/api/v1/sap/personelservice/sirketler/{firmaKodu}
          #is-liste: http://10.67.97.20:32737/api/v1/sap/islerservice/isler         
          organizasyon-liste: https://apigwtest.erdemir.com.tr/int/dev/sapservice/api/v1/sap/organizasyonservice/organizasyonlar
          personel-list-by-firma-kodu: https://apigwtest.erdemir.com.tr/int/dev/sapservice/api/v1/sap/personelservice/sirketler/{firmaKodu}
          is-liste: https://apigwtest.erdemir.com.tr/int/dev/sapservice/api/v1/sap/islerservice/isler
        satis:
          ardiye:
            acma: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/tesellumardiye/acma
            durdurma: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/tesellumardiye/durdurma
            ardiye-bilgi-sorgula: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/tesellumardiye/tesellumArdiyeTarihiSorgula
          bulten:
            diibUygunluguKontrol: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/bultenyonetimi/diibUygunluguKontrol
          faturaya-baz-bulten-bilgileri:
            getir: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/bultenyonetimi/faturayaBazBultenBilgiGetir
          gumruk-beyanname:
            liste: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/gumrukBeyannameListele
            getir: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/gumrukBeyannameNo
            #liste: https://kurumsaldevl-was1.erdemir.com.tr/satis-be/satis/api/v1/stokyonetimi/gumrukBeyannameListele
            #getir: https://kurumsaldevl-was1.erdemir.com.tr/satis-be/satis/api/v1/stokyonetimi/gumrukBeyannameNo
          stok:
            romanya: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/romanyaDepoMamulTuket
            bulten-etiket-degistir: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/bultenEtiketDegistir
        sevk-bilgilendirme:
          satis-sevk-bildirim: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/sevkBildirimi
          satis-sevk-iptal-bildirim: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/stokyonetimi/sevkBildirimiIptal
          erdemir-kalite-etiket-sevk-bildirim: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketSevkEt
          erdemir-kalite-etiket-sevk-iptal-bildirim: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketSevkEtIptal
          erdemir-kalite-etiket-ersem-sevk-bildirim: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketErsemFasonaSevkBilgisiGonder
          erdemir-kalite-etiket-agirlik-puantaj-bildirim: https://apigwtest.erdemir.com.tr/int/dev/euysent/kaliteyonetimi/etiketIslemleri/getEtiketAgirlikvePuantaj
          erdemir-kalite-test-etiket-bildirim: https://apigwtest.erdemir.com.tr/int/dev/tcent/testsertifikalari/testetiketbilgileri/getEtiketBilgileri
          isdemir-uys-sevk-bildirim: https://apigwtest.erdemir.com.tr/int/dev/iuys/uysservis/service/sevkiyatIslemleri/etiketSevk
          isdemir-uys-sevk-iptal-bildirim: https://apigwtest.erdemir.com.tr/int/dev/iuys/uysservis/service/sevkiyatIslemleri/etiketSevkIptal
          satis-iade-sevk-bildirim: https://apigwtest.erdemir.com.tr/int/dev/mysent/satis/api/v1/ext/sikayetyonetimi/iadePuantajGuncelle
      server:
        etiket:
          kaydet: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/kaydet
          hold: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/hold
          unhold: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/unHold
          iptal: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/iptal
          barkodGuncelle: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/barkodGuncelle
          degistir: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/degistir
          guncelle: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/guncelle
          teslimOnayiBekleyenEtiketListele: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/teslimOnayiBekleyenEtiketListele
          teslimOnayiBekleyenEtiketOnay: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/etiket/teslimOnayiBekleyenEtiketOnay          
          etiketAdresListele: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/depo/etiketAdresListele
          adresGuncelle: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/ambar/adresGuncelle
          iadeBultenIptal: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/iade/iadeBultenIptal
          iadeSiparisIptal: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/iade/iadeSiparisIptal
          iadeSiparisKaydet: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/iade/iadeSiparisKaydet
          iadeBultenKaydet: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/iade/iadeBultenKaydet
        depo:
          adresListele: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/depo/adresListele
        sevkiyat-test:
          deniz-yolu-araci-kaydet: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/lys/deniz-yolu-araci/kaydet
          tartim-kaydet: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/tartim/tartim-kaydet
          bulten-islem-kontrol: https://kurumsaldevl-was1.erdemir.com.tr/sevkiyat-be/sevkiyat/api/v1/bulten/bultenIslemKontrol

bbys:
  username: satisws@erdemir
  password: 111111
  server:
    url: bbysconttest.erdemir.erdgrp.intra
  apipath:
    url: /otcs/cs.exe/api/v1/

